In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Amazon Sale Report.csv')

In [4]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Category,Size,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,Set,S,NaN,0.0,INR,647.62,mumbai,Maharashtra,400081.0,IN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,kurta,3XL,Shipped,1.0,INR,406.00,bengaluru,Karnataka,560085.0,IN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,kurta,XL,Shipped,1.0,INR,329.00,navi mumbai,Maharashtra,410210.0,IN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,Western Dress,L,NaN,0.0,INR,753.33,puducherry,Puducherry,605008.0,IN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,Top,3XL,Shipped,1.0,INR,574.00,chennai,Tamil Nadu,600073.0,IN

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.shape

(47009, 17)

In [10]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Category', 'Size', 'Courier Status', 'Qty',
       'currency', 'Amount', 'ship-city', 'ship-state', 'ship-postal-code',
       'ship-country'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47009 entries, 0 to 47008
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   index               47009 non-null  int64
 1   Order ID            47009 non-null  object
 2   Date                47009 non-null  object
 3   Status              47009 non-null  object
 4   Fulfilment          47009 non-null  object
 5   Sales Channel       47009 non-null  object
 6   ship-service-level  47008 non-null  object
 7   Category            47008 non-null  object
 8   Size                47008 non-null  object
 9   Courier Status      44278 non-null  object
 10  Qty                 47008 non-null  float64
 11  currency            44161 non-null  object
 12  Amount              44161 non-null  float64
 13  ship-city           46995 non-null  object
 14  ship-state          46995 non-null  object
 15  ship-postal-code    46995 non-null  float64
 16  ship-country        46995 non-null  object
dtypes: float64(3), int64(1), object(13)
memory usage: 6.1+ MB

In [13]:
df['Date'] = pd.to_datetime(df['Date'])
df['Qty'] = df['Qty'].astype('Int64')
df['ship-postal-code'] = df['ship-postal-code'].astype('Int64')

/tmp/ipykernel_1383/1425251788.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date'] = pd.to_datetime(df['Date'])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47009 entries, 0 to 47008
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   index               47009 non-null  int64
 1   Order ID            47009 non-null  object
 2   Date                47009 non-null  datetime64[ns]
 3   Status              47009 non-null  object
 4   Fulfilment          47009 non-null  object
 5   Sales Channel       47009 non-null  object
 6   ship-service-level  47008 non-null  object
 7   Category            47008 non-null  object
 8   Size                47008 non-null  object
 9   Courier Status      44278 non-null  object
 10  Qty                 47008 non-null  Int64
 11  currency            44161 non-null  object
 12  Amount              44161 non-null  float64
 13  ship-city           46995 non-null  object
 14  ship-state          46995 non-null  object
 15  ship-postal-code    46995 non-null  Int64
 16  ship-country        46995 non-null  object
dtypes: Int64(2), datetime64[ns](1), float64(1), int64(1), object(12)
memory usage: 6.2+ MB

In [16]:
df.isnull().sum()

index                    0
Order ID                 0
Date                     0
Status                   0
Fulfilment               0
Sales Channel            0
ship-service-level       1
Category                 1
Size                     1
Courier Status        2731
Qty                      1
currency              2848
Amount                2848
ship-city               14
ship-state              14
ship-postal-code        14
ship-country            14
dtype: int64

In [19]:
df['Courier Status'].unique()

array([nan, 'Shipped', 'Cancelled', 'Unshipped'], dtype=object)

In [23]:
df['Courier Status'].value_counts(dropna=False)

Courier Status
Shipped      40125
NaN           2731
Cancelled     2122
Unshipped     2031
Name: count, dtype: int64

In [25]:
df['Status'].value_counts(dropna=False)

Status
Shipped                          27569
Shipped - Delivered to Buyer     11757
Cancelled                         6797
Shipped - Returned to Seller       870
Shipped - Rejected by Buyer          6
Shipped - Picked Up                  4
Shipped - Lost in Transit            2
Shipped - Returning to Seller        2
Shipped - Out for Delivery           1
Pending                              1
Name: count, dtype: int64

In [24]:
pd.crosstab(df['Status'], df['Courier Status'], dropna=False)

Courier Status                 Cancelled  Shipped  Unshipped   NaN
Status
Cancelled                           2094        0       1978  2725
Pending                                0        0          1     0
Shipped                               28    27489         52     0
Shipped - Delivered to Buyer           0    11751          0     6
Shipped - Lost in Transit              0        2          0     0
Shipped - Out for Delivery             0        1          0     0
Shipped - Picked Up                    0        4          0     0
Shipped - Rejected by Buyer            0        6          0     0
Shipped - Returned to Seller           0      870          0     0
Shipped - Returning to Seller          0        2          0     0

In [26]:
mask = (df['Courier Status'].isna()) & (df['Status'] == 'Cancelled')

df.loc[mask, 'Courier Status'] = 'Cancelled'

In [28]:
df['Courier Status'].isnull().sum()

np.int64(6)

In [29]:
df['Courier Status'] = df['Courier Status'].fillna('Shipped')

In [30]:
df['Courier Status'].isnull().sum()

np.int64(0)

In [31]:
df.isnull().sum()

index                    0
Order ID                 0
Date                     0
Status                   0
Fulfilment               0
Sales Channel            0
ship-service-level       1
Category                 1
Size                     1
Courier Status           0
Qty                      1
currency              2848
Amount                2848
ship-city               14
ship-state              14
ship-postal-code        14
ship-country            14
dtype: int64

In [32]:
df[df['currency'].isna()][['Status', 'Amount']].head()

       Status  Amount
8   Cancelled     NaN
29  Cancelled     NaN
65  Cancelled     NaN
84  Cancelled     NaN
95  Cancelled     NaN

In [33]:
pd.crosstab(df['Status'], df['currency'], dropna=False)

currency                         INR   NaN
Status
Cancelled                       4035  2762
Pending                            1     0
Shipped                        27489    80
Shipped - Delivered to Buyer   11751     6
Shipped - Lost in Transit          2     0
Shipped - Out for Delivery         1     0
Shipped - Picked Up                4     0
Shipped - Rejected by Buyer        6     0
Shipped - Returned to Seller     870     0
Shipped - Returning to Seller      2     0

In [34]:
df['currency'].unique()

array(['INR', nan], dtype=object)

In [35]:
df['currency'] = df['currency'].fillna('INR')

In [36]:
df.isnull().sum()

index                    0
Order ID                 0
Date                     0
Status                   0
Fulfilment               0
Sales Channel            0
ship-service-level       1
Category                 1
Size                     1
Courier Status           0
Qty                      1
currency                 0
Amount                2848
ship-city               14
ship-state              14
ship-postal-code        14
ship-country            14
dtype: int64

In [41]:
df[['Amount','Courier Status']]

       Amount Courier Status
0      647.62      Cancelled
1      406.00        Shipped
2      329.00        Shipped
3      753.33      Cancelled
4      574.00        Shipped
...       ...            ...
47004  339.00        Shipped
47005  984.00        Shipped
47006  799.00        Shipped
47007  449.00        Shipped
47008     NaN        Shipped

[47009 rows x 2 columns]

In [45]:
(
    df['currency'].isna() &
    df['Amount'].isna()
).sum()

np.int64(0)

In [46]:
df[df['currency'].isna()][['Amount']].isna().sum()

Amount    0
dtype: int64

In [48]:
df[df['currency'].isna()][['Status', 'Amount']].head(10)

Empty DataFrame
Columns: [Status, Amount]
Index: []

In [49]:
df[df['currency'].isna()][['Amount']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Amount  0 non-null      float64
dtypes: float64(1)
memory usage: 0.0 bytes

In [50]:
df['Amount'].isna().sum()

np.int64(2848)

In [51]:
pd.crosstab(
    df['currency'].isna(),
    df['Amount'].isna()
)

Amount    False  True
currency
False     44161   2848

In [55]:
df['Amount'] = df['Amount'].fillna(0)

In [56]:
df.isnull().sum()

index                  0
Order ID               0
Date                   0
Status                 0
Fulfilment             0
Sales Channel          0
ship-service-level     1
Category               1
Size                   1
Courier Status         0
Qty                    1
currency               0
Amount                 0
ship-city             14
ship-state            14
ship-postal-code      14
ship-country          14
dtype: int64

In [64]:
df[
    df['ship-city'].isna() &
    df['ship-state'].isna() &
    df['ship-postal-code'].isna() &
    df['ship-country'].isna()
].shape

(14, 17)

In [65]:
df[
    df['ship-city'].isna()
][['Status', 'Order ID']]

                             Status             Order ID
1871                        Shipped  404-0566904-4825137
1872                        Shipped  404-0566904-4825137
8752                        Shipped  406-4003386-8768363
11215                       Shipped  402-0107720-7057168
13252                     Cancelled  407-4532637-8415521
15688                       Shipped  404-9229894-8608305
16787  Shipped - Delivered to Buyer  402-4919636-4333150
18351                       Shipped  405-4927647-8064368
22930  Shipped - Returned to Seller  402-8628677-0457954
24986                     Cancelled  406-4079063-8291520
30379  Shipped - Delivered to Buyer  404-7506843-7913132
37963                     Cancelled  407-3064376-9158743
37964                     Cancelled  407-3064376-9158743
47008  Shipped - Delivered to Buyer  405-4958015-0721136

In [66]:
df[df['ship-city'].isna()]['Status'].value_counts()

Status
Shipped                         6
Cancelled                       4
Shipped - Delivered to Buyer    3
Shipped - Returned to Seller    1
Name: count, dtype: int64

In [67]:
df.dropna(
    subset=[
        'ship-city',
        'ship-state',
        'ship-postal-code',
        'ship-country'
    ],
    inplace=True
)

In [69]:
df.to_csv('amazon_sales_cleaned.csv', index=False)

In [70]:
sorted(df['ship-state'].dropna().unique())

['Andaman & Nicobar ',
 'Andhra Pradesh',
 'Apo',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra And Nagar',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu & Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Ladakh',
 'Lakshadweep',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'New Delhi',
 'Nl',
 'Odisha',
 'Orissa',
 'Pb',
 'Puducherry',
 'Punjab',
 'Punjab/Mohali/Zirakpur',
 'Rajasthan',
 'Rajshthan',
 'Rj',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']

In [73]:
state_mapping = {
    'New Delhi': 'Delhi',
    'Orissa': 'Odisha',
    'Rj': 'Rajasthan',
    'Rajshthan': 'Rajasthan',
    'Pb': 'Punjab',
    'Punjab/Mohali/Zirakpur': 'Punjab',
    'Nl': 'Nagaland'
}

In [72]:
df['ship-state'] = (
    df['ship-state']
    .str.strip()
    .str.title()
)

In [74]:
df['ship-state'] = df['ship-state'].replace(state_mapping)

In [75]:
df[df['ship-state'] == 'Apo']

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Category,Size,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country
45187,45187,405-0034289-0259545,2022-04-03,Cancelled,Amazon,Amazon.in,Expedited,Set,S,Cancelled,0,INR,0.0,apo,Apo,959121,IN

In [76]:
df['ship-state'].value_counts().loc[['Apo']]

ship-state
Apo    1
Name: count, dtype: int64

In [77]:
df = df[df['ship-state'] != 'Apo']

In [78]:
sorted(df['ship-state'].unique())

['Andaman & Nicobar',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra And Nagar',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu & Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Ladakh',
 'Lakshadweep',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']

In [80]:
df.isnull().sum()

index                 0
Order ID              0
Date                  0
Status                0
Fulfilment            0
Sales Channel         0
ship-service-level    0
Category              0
Size                  0
Courier Status        0
Qty                   0
currency              0
Amount                0
ship-city             0
ship-state            0
ship-postal-code      0
ship-country          0
dtype: int64