#### How can the company optimize advertising spend by identifying which advertising channels, platforms, and creative formats deliver the highest click-through rates at the lowest cost, while staying within budget?

In [1]:
import pandas as pd

In [8]:
df = pd.read_csv(r'C:\Users\Swayam B Solanki\Documents\SQL 30 Days Challenge\Day 4\data\Marketing campaign dataset.csv')

In [9]:
df.head()

,campaign_item_id,no_of_days,time,ext_service_id,ext_service_name,creative_id,creative_width,creative_height,search_tags,template_id,...,exchange_rate,media_cost_usd,position_in_content,unique_reach,total_reach,search_tag_cat,cmi_currency_code,timezone,weekday_cat,keywords
0,2733,7,01-05-2022,128,Facebook Ads,1000,300.0,250.0,#The Power of X,90.0,...,1,14.058514,NaN,NaN,NaN,Others,SGD,Asia/Singapore,week_end,delicate bracelets
1,2733,8,02-05-2022,16,DV360,1000,300.0,250.0,#Be Bold. Be X,90.0,...,1,99.633496,NaN,NaN,NaN,Others,SGD,Asia/Singapore,week_day,summer jewelry
2,2733,9,03-05-2022,128,Facebook Ads,1000,300.0,250.0,#Embrace Your Individuality with X,90.0,...,1,109.419677,NaN,NaN,NaN,Others,SGD,Asia/Singapore,week_day,artisan jewelry
3,2733,10,04-05-2022,128,Facebook Ads,1000,300.0,250.0,#Be Bold. Be X,90.0,...,1,115.209499,NaN,NaN,NaN,Others,SGD,Asia/Singapore,week_day,layered bracelets
4,2733,11,05-05-2022,4,Google Ads,1000,300.0,250.0,#Be Bold. Be X,90.0,...,1,66.990104,NaN,NaN,NaN,Others,SGD,Asia/Singapore,week_day,minimalist jewelry

In [10]:
df.columns

Index(['campaign_item_id', 'no_of_days', 'time', 'ext_service_id',
       'ext_service_name', 'creative_id', 'creative_width', 'creative_height',
       'search_tags', 'template_id', 'landing_page', 'advertiser_id',
       'advertiser_name', 'network_id', 'approved_budget',
       'advertiser_currency', 'channel_id', 'channel_name', 'max_bid_cpm',
       'network_margin', 'campaign_budget_usd', 'impressions', 'clicks',
       'stats_currency', 'currency_code', 'exchange_rate', 'media_cost_usd',
       'position_in_content', 'unique_reach', 'total_reach', 'search_tag_cat',
       'cmi_currency_code', 'timezone', 'weekday_cat', 'keywords'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72612 entries, 0 to 72611
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   campaign_item_id     72612 non-null  int64
 1   no_of_days           72612 non-null  int64
 2   time                 72612 non-null  object
 3   ext_service_id       72612 non-null  int64
 4   ext_service_name     72612 non-null  object
 5   creative_id          72612 non-null  int64
 6   creative_width       69200 non-null  float64
 7   creative_height      69200 non-null  float64
 8   search_tags          72612 non-null  object
 9   template_id          69200 non-null  float64
 10  landing_page         72612 non-null  object
 11  advertiser_id        72612 non-null  int64
 12  advertiser_name      72612 non-null  object
 13  network_id           72612 non-null  int64
 14  approved_budget      72206 non-null  float64
 15  advertiser_currency  72612 non-null  object
 16  channel_id           72612 non-null  int64
 17  channel_name         72612 non-null  object
 18  max_bid_cpm          7406 non-null   float64
 19  network_margin       72612 non-null  int64
 20  campaign_budget_usd  72612 non-null  float64
 21  impressions          72612 non-null  int64
 22  clicks               72612 non-null  int64
 23  stats_currency       72612 non-null  object
 24  currency_code        72612 non-null  object
 25  exchange_rate        72612 non-null  int64
 26  media_cost_usd       72612 non-null  float64
 27  position_in_content  0 non-null      float64
 28  unique_reach         0 non-null      float64
 29  total_reach          0 non-null      float64
 30  search_tag_cat       72612 non-null  object
 31  cmi_currency_code    72612 non-null  object
 32  timezone             72612 non-null  object
 33  weekday_cat          72612 non-null  object
 34  keywords             72612 non-null  object
dtypes: float64(10), int64(11), object(14)
memory usage: 19.4+ MB

In [16]:
df[['position_in_content', 'unique_reach', 'total_reach']].isnull().sum()

position_in_content    72612
unique_reach           72612
total_reach            72612
dtype: int64

In [17]:
df.shape

(72612, 35)

In [18]:
df = df.drop(columns=['position_in_content', 'unique_reach', 'total_reach'])

In [19]:
df.dtypes

campaign_item_id         int64
no_of_days               int64
time                    object
ext_service_id           int64
ext_service_name        object
creative_id              int64
creative_width         float64
creative_height        float64
search_tags             object
template_id            float64
landing_page            object
advertiser_id            int64
advertiser_name         object
network_id               int64
approved_budget        float64
advertiser_currency     object
channel_id               int64
channel_name            object
max_bid_cpm            float64
network_margin           int64
campaign_budget_usd    float64
impressions              int64
clicks                   int64
stats_currency          object
currency_code           object
exchange_rate            int64
media_cost_usd         float64
search_tag_cat          object
cmi_currency_code       object
timezone                object
weekday_cat             object
keywords                object
dtype: object

In [22]:
df.isnull().sum()

campaign_item_id           0
no_of_days                 0
time                       0
ext_service_id             0
ext_service_name           0
creative_id                0
creative_width          3412
creative_height         3412
search_tags                0
template_id             3412
landing_page               0
advertiser_id              0
advertiser_name            0
network_id                 0
approved_budget          406
advertiser_currency        0
channel_id                 0
channel_name               0
max_bid_cpm            65206
network_margin             0
campaign_budget_usd        0
impressions                0
clicks                     0
stats_currency             0
currency_code              0
exchange_rate              0
media_cost_usd             0
search_tag_cat             0
cmi_currency_code          0
timezone                   0
weekday_cat                0
keywords                   0
dtype: int64

In [24]:
df.shape

(72612, 32)

In [25]:

# Drop columns that are not required for the current business analysis.
# Keep the original dataset unchanged.

columns_to_drop = [
    'search_tags',          # Exclude initially; keywords and search_tag_cat
                            # can support the planned keyword analysis.

    'landing_page',         # Not needed for channel, platform, or creative
                            # performance metrics; useful for landing-page analysis.

    'advertiser_currency',  # Exclude only after confirming USD-normalized costs
                            # are sufficient for the analysis.

    'stats_currency',       # Currency metadata; retain in raw data for validation.

    'currency_code',        # Currency metadata; retain if currency validation is needed.

    'cmi_currency_code',    # Currency metadata; verify its purpose before excluding.

    'exchange_rate',        # Not needed if costs are consistently normalized to USD.

    'timezone',             # Exclude for initial analysis if timestamps are already
                            # standardized to the reporting timezone.

    'network_margin',       # Exclude from the initial scope unless its definition
                            # is relevant to advertising cost or profitability.
]

# Create an analytical copy
df_cleaned = df.drop(columns=columns_to_drop, errors='ignore')

# Check the result
print("Original shape:", df.shape)
print("Cleaned shape:", df_cleaned.shape)
print("Remaining columns:", df_cleaned.columns.tolist())

Original shape: (72612, 32)
Cleaned shape: (72612, 23)
Remaining columns: ['campaign_item_id', 'no_of_days', 'time', 'ext_service_id', 'ext_service_name', 'creative_id', 'creative_width', 'creative_height', 'template_id', 'advertiser_id', 'advertiser_name', 'network_id', 'approved_budget', 'channel_id', 'channel_name', 'max_bid_cpm', 'campaign_budget_usd', 'impressions', 'clicks', 'media_cost_usd', 'search_tag_cat', 'weekday_cat', 'keywords']

In [26]:

# Check missing values and their percentages
missing_summary = pd.DataFrame({
    'Missing_Count': df.isnull().sum(),
    'Missing_Percentage': (df.isnull().mean() * 100).round(2)
})

missing_summary = (
    missing_summary[missing_summary['Missing_Count'] > 0]
    .sort_values('Missing_Percentage', ascending=False)
)

print(missing_summary)

                 Missing_Count  Missing_Percentage
max_bid_cpm              65206               89.80
creative_width            3412                4.70
creative_height           3412                4.70
template_id               3412                4.70
approved_budget            406                0.56

In [27]:

# Check whether missing creative metadata occurs on the same records
creative_cols = ['creative_width', 'creative_height', 'template_id']

print(df[creative_cols].isnull().sum())

print(
    "Rows missing all three creative fields:",
    df[creative_cols].isnull().all(axis=1).sum()
)

print(
    "Rows missing approved budget:",
    df['approved_budget'].isnull().sum()
)

creative_width     3412
creative_height    3412
template_id        3412
dtype: int64
Rows missing all three creative fields: 3412
Rows missing approved budget: 406

In [28]:

# Create a copy for advertising performance analysis
df_cleaned = df.drop(columns=['max_bid_cpm'], errors='ignore').copy()

# Keep rows with valid data for the core metrics
df_cleaned = df_cleaned.dropna(
    subset=['campaign_item_id', 'clicks', 'impressions', 'media_cost_usd']
)

# Check the result
print("Original dataset:", df.shape)
print("Cleaned dataset:", df_cleaned.shape)
print("Remaining missing values:")
print(df_cleaned.isnull().sum()[df_cleaned.isnull().sum() > 0])

Original dataset: (72612, 32)
Cleaned dataset: (72612, 31)
Remaining missing values:
creative_width     3412
creative_height    3412
template_id        3412
approved_budget     406
dtype: int64

In [34]:
df_cleaned.duplicated().sum()

np.int64(0)

In [35]:
df_cleaned.describe()

,campaign_item_id,no_of_days,ext_service_id,creative_id,creative_width,creative_height,template_id,advertiser_id,network_id,approved_budget,channel_id,network_margin,campaign_budget_usd,impressions,clicks,exchange_rate,media_cost_usd
count,72612.000000,72612.000000,72612.000000,72612.000000,69200.000000,69200.000000,69200.000000,72612.000000,72612.000000,7.220600e+04,72612.000000,72612.0,72612.000000,72612.000000,72612.000000,72612.0,72612.000000
mean,3130.143282,27.036344,49.449127,7450.124842,267.810694,223.175578,83.082659,6195.862213,345.272861,1.258064e+05,21.847780,0.0,617.630284,1370.161847,52.696386,1.0,11.819999
std,142.154918,25.479175,55.881324,4062.384982,92.848075,77.373396,20.847618,387.864576,23.707191,5.626204e+05,23.759286,0.0,1354.606620,3702.699962,377.308103,0.0,48.370659
min,2733.000000,0.000000,4.000000,1000.000000,0.000000,0.000000,23.000000,4756.000000,188.000000,4.000000e+02,1.000000,0.0,2.452316,511.000000,2.000000,1.0,0.000000
25%,3148.000000,9.000000,4.000000,3725.000000,300.000000,250.000000,90.000000,6319.000000,353.000000,6.000000e+03,4.000000,0.0,205.994550,526.000000,5.000000,1.0,0.435791
50%,3173.000000,19.000000,16.000000,7855.000000,300.000000,250.000000,90.000000,6385.000000,353.000000,1.000000e+04,8.000000,0.0,377.656676,577.000000,8.000000,1.0,1.709001
75%,3202.000000,37.000000,128.000000,10995.000000,300.000000,250.000000,90.000000,6394.000000,353.000000,1.500000e+04,32.000000,0.0,755.313351,816.000000,13.000000,1.0,8.276369
max,3960.000000,118.000000,128.000000,15605.000000,300.000000,250.000000,93.000000,6490.000000,353.000000,6.000000e+06,64.000000,0.0,39559.896160,153959.000000,31807.000000,1.0,2295.028945

In [38]:
df_cleaned.dtypes

campaign_item_id         int64
no_of_days               int64
time                    object
ext_service_id           int64
ext_service_name        object
creative_id              int64
creative_width         float64
creative_height        float64
search_tags             object
template_id            float64
landing_page            object
advertiser_id            int64
advertiser_name         object
network_id               int64
approved_budget        float64
advertiser_currency     object
channel_id               int64
channel_name            object
network_margin           int64
campaign_budget_usd    float64
impressions              int64
clicks                   int64
stats_currency          object
currency_code           object
exchange_rate            int64
media_cost_usd         float64
search_tag_cat          object
cmi_currency_code       object
timezone                object
weekday_cat             object
keywords                object
dtype: object

In [39]:

import pandas as pd

# 1. Convert time to datetime
df_cleaned['time'] = pd.to_datetime(
    df_cleaned['time'],
    errors='coerce'
)

# 2. Convert whole-number creative attributes to nullable integers
# Nullable Int64 preserves missing values instead of failing.
integer_columns = [
    'creative_width',
    'creative_height',
    'template_id'
]

for col in integer_columns:
    df_cleaned[col] = pd.to_numeric(
        df_cleaned[col],
        errors='coerce'
    ).astype('Int64')

# 3. Ensure financial columns are numeric
financial_columns = [
    'approved_budget',
    'campaign_budget_usd',
    'media_cost_usd'
]

for col in financial_columns:
    df_cleaned[col] = pd.to_numeric(
        df_cleaned[col],
        errors='coerce'
    )

# 4. Verify the updated data types
print(df_cleaned.dtypes)

campaign_item_id                int64
no_of_days                      int64
time                   datetime64[ns]
ext_service_id                  int64
ext_service_name               object
creative_id                     int64
creative_width                  Int64
creative_height                 Int64
search_tags                    object
template_id                     Int64
landing_page                   object
advertiser_id                   int64
advertiser_name                object
network_id                      int64
approved_budget               float64
advertiser_currency            object
channel_id                      int64
channel_name                   object
network_margin                  int64
campaign_budget_usd           float64
impressions                     int64
clicks                          int64
stats_currency                 object
currency_code                  object
exchange_rate                   int64
media_cost_usd                float64
search_tag_cat                 object
cmi_currency_code              object
timezone                       object
weekday_cat                    object
keywords                       object
dtype: object

In [40]:

# Check missing values after conversion
print("Missing values after conversion:")
print(df_cleaned[
    ['time', 'creative_width', 'creative_height',
     'template_id', 'approved_budget']
].isnull().sum())

# Inspect sample records
print(df_cleaned[
    ['time', 'creative_width', 'creative_height',
     'template_id', 'approved_budget']
].head())

Missing values after conversion:
time               44422
creative_width      3412
creative_height     3412
template_id         3412
approved_budget      406
dtype: int64
        time  creative_width  creative_height  template_id  approved_budget
0 2022-01-05             300              250           90            400.0
1 2022-02-05             300              250           90            400.0
2 2022-03-05             300              250           90            400.0
3 2022-04-05             300              250           90            400.0
4 2022-05-05             300              250           90            400.0

In [41]:

# Inspect original time values before conversion
print(df['time'].head(20).to_list())

print("\nMost common timestamp formats / values:")
print(df['time'].astype(str).value_counts().head(20))

# Find examples that failed conversion
parsed_time = pd.to_datetime(df['time'], errors='coerce')
invalid_mask = parsed_time.isna() & df['time'].notna()

print("\nExamples of values that failed conversion:")
print(df.loc[invalid_mask, 'time'].astype(str).head(30).to_list())

['01-05-2022', '02-05-2022', '03-05-2022', '04-05-2022', '05-05-2022', '31-05-2022', '01-06-2022', '02-06-2022', '03-06-2022', '04-06-2022', '05-06-2022', '06-06-2022', '07-06-2022', '08-06-2022', '09-06-2022', '10-06-2022', '11-06-2022', '12-06-2022', '13-06-2022', '14-06-2022']

Most common timestamp formats / values:
time
22-10-2022    955
23-10-2022    948
21-10-2022    903
31-10-2022    809
30-10-2022    807
24-10-2022    782
25-10-2022    777
26-10-2022    773
28-10-2022    772
29-10-2022    770
19-10-2022    769
27-10-2022    765
18-10-2022    744
20-10-2022    721
17-10-2022    719
14-10-2022    684
15-10-2022    678
16-10-2022    672
12-10-2022    648
07-10-2022    647
Name: count, dtype: int64

Examples of values that failed conversion:
['31-05-2022', '13-06-2022', '14-06-2022', '15-06-2022', '16-06-2022', '17-06-2022', '18-06-2022', '19-06-2022', '20-06-2022', '21-06-2022', '22-06-2022', '23-06-2022', '24-06-2022', '25-06-2022', '26-06-2022', '27-06-2022', '28-06-2022', '29-06-2022', '30-06-2022', '13-07-2022', '14-07-2022', '15-07-2022', '16-07-2022', '17-07-2022', '18-07-2022', '19-07-2022', '20-07-2022', '21-07-2022', '22-07-2022', '23-07-2022']

In [45]:
df_cleaned['time'] = pd.to_datetime(
    df_cleaned['time'],
    format='%Y-%m-%d',
    errors='coerce'
)

In [46]:
print("Missing timestamps:", df_cleaned['time'].isna().sum())
print("Valid timestamps:", df_cleaned['time'].notna().sum())
print(df_cleaned['time'].head(10))

Missing timestamps: 44422
Valid timestamps: 28190
0   2022-01-05
1   2022-02-05
2   2022-03-05
3   2022-04-05
4   2022-05-05
5          NaT
6   2022-01-06
7   2022-02-06
8   2022-03-06
9   2022-04-06
Name: time, dtype: datetime64[ns]

In [47]:

# Parse the original column for diagnosis
parsed = pd.to_datetime(df['time'], errors='coerce')

# Identify values that failed conversion
invalid_mask = parsed.isna() & df['time'].notna()

# Display examples
print("Failed values:")
print(df.loc[invalid_mask, 'time'].astype(str).head(30).to_list())

# Check the original column's most common values
print("\nSample original values:")
print(df['time'].astype(str).sample(
    min(30, len(df)), random_state=42
).to_list())

Failed values:
['31-05-2022', '13-06-2022', '14-06-2022', '15-06-2022', '16-06-2022', '17-06-2022', '18-06-2022', '19-06-2022', '20-06-2022', '21-06-2022', '22-06-2022', '23-06-2022', '24-06-2022', '25-06-2022', '26-06-2022', '27-06-2022', '28-06-2022', '29-06-2022', '30-06-2022', '13-07-2022', '14-07-2022', '15-07-2022', '16-07-2022', '17-07-2022', '18-07-2022', '19-07-2022', '20-07-2022', '21-07-2022', '22-07-2022', '23-07-2022']

Sample original values:
['30-07-2022', '27-10-2022', '26-10-2022', '23-10-2022', '04-12-2022', '10-12-2022', '23-06-2022', '05-12-2022', '06-08-2022', '06-07-2022', '17-10-2022', '30-11-2022', '05-09-2022', '13-11-2022', '23-08-2022', '18-11-2022', '09-09-2022', '19-08-2022', '15-08-2022', '16-11-2022', '08-12-2022', '06-08-2022', '02-12-2022', '19-10-2022', '06-07-2022', '11-11-2022', '03-07-2022', '11-10-2022', '13-07-2022', '13-07-2022']

In [48]:

# Parse both date formats safely
date_text = df['time'].astype('string').str.strip()

# First format: YYYY-MM-DD
dates_iso = pd.to_datetime(
    date_text,
    format='%Y-%m-%d',
    errors='coerce'
)

# Second format: DD-MM-YYYY
dates_dmy = pd.to_datetime(
    date_text,
    format='%d-%m-%Y',
    errors='coerce'
)

# Combine both results
df_cleaned['time'] = dates_iso.fillna(dates_dmy)

# Verify the result
print("Missing timestamps:", df_cleaned['time'].isna().sum())
print("Valid timestamps:", df_cleaned['time'].notna().sum())
print(df_cleaned['time'].head(10))

Missing timestamps: 0
Valid timestamps: 72612
0   2022-05-01
1   2022-05-02
2   2022-05-03
3   2022-05-04
4   2022-05-05
5   2022-05-31
6   2022-06-01
7   2022-06-02
8   2022-06-03
9   2022-06-04
Name: time, dtype: datetime64[ns]

In [49]:
# Check completely duplicated rows
print("Exact duplicate rows:", df_cleaned.duplicated().sum())

# Check repeated campaign item IDs
print(
    "Rows with repeated campaign_item_id:",
    df_cleaned.duplicated(subset=['campaign_item_id']).sum()
)

# Inspect repeated IDs
print(
    df_cleaned[
        df_cleaned.duplicated(
            subset=['campaign_item_id'], keep=False
        )
    ].head(10)
)

Exact duplicate rows: 0
Rows with repeated campaign_item_id: 72455
   campaign_item_id  no_of_days       time  ext_service_id ext_service_name  \
0              2733           7 2022-05-01             128     Facebook Ads
1              2733           8 2022-05-02              16            DV360
2              2733           9 2022-05-03             128     Facebook Ads
3              2733          10 2022-05-04             128     Facebook Ads
4              2733          11 2022-05-05               4       Google Ads
5              2766          53 2022-05-31               4       Google Ads
6              2766          54 2022-06-01               4       Google Ads
7              2766          55 2022-06-02              16            DV360
8              2766          56 2022-06-03              16            DV360
9              2766          57 2022-06-04             128     Facebook Ads

   creative_id  creative_width  creative_height  \
0         1000             300              250
1         1000             300              250
2         1000             300              250
3         1000             300              250
4         1000             300              250
5         1005               0                0
6         1005               0                0
7         1005               0                0
8         1005               0                0
9         1005               0                0

                                search_tags  template_id  ... clicks  \
0                           #The Power of X           90  ...      8
1                            #Be Bold. Be X           90  ...     44
2        #Embrace Your Individuality with X           90  ...     32
3                            #Be Bold. Be X           90  ...     48
4                            #Be Bold. Be X           90  ...     20
5                            #Be Bold. Be X           23  ...     11
6    #The Ultimate Fashion Statement with X           23  ...     18
7    #The Ultimate Fashion Statement with X           23  ...     12
8  #The X Factor - Fashion for the Fearless           23  ...      5
9                            #Be Bold. Be X           23  ...      8

   stats_currency currency_code  exchange_rate  media_cost_usd search_tag_cat  \
0             SGD           SGD              1       14.058514         Others
1             SGD           SGD              1       99.633496         Others
2             SGD           SGD              1      109.419677         Others
3             SGD           SGD              1      115.209499         Others
4             SGD           SGD              1       66.990104         Others
5             USD           USD              1       35.673124        Youtube
6             USD           USD              1       43.150656        Youtube
7             USD           USD              1       31.436393        Youtube
8             USD           USD              1        5.409166        Youtube
9             USD           USD              1        5.965384        Youtube

   cmi_currency_code          timezone  weekday_cat                   keywords
0                SGD    Asia/Singapore     week_end         delicate bracelets
1                SGD    Asia/Singapore     week_day             summer jewelry
2                SGD    Asia/Singapore     week_day            artisan jewelry
3                SGD    Asia/Singapore     week_day          layered bracelets
4                SGD    Asia/Singapore     week_day         minimalist jewelry
5                USD  America/New_York     week_day           beaded bracelets
6                USD  America/New_York     week_day             bridal jewelry
7                USD  America/New_York     week_day  unique and trendy jewelry
8                USD  America/New_York     week_day           clip-on earrings
9                USD  America/New_York     week_day           bohemian jewelry

[10 rows x 31 columns]

In [50]:
# Values that should not be negative
for col in ['clicks', 'impressions', 'media_cost_usd']:
    print(f"{col} — negative values:", (df_cleaned[col] < 0).sum())

# Clicks should generally not exceed impressions
print(
    "Rows where clicks exceed impressions:",
    (df_cleaned['clicks'] > df_cleaned['impressions']).sum()
)

clicks — negative values: 0
impressions — negative values: 0
media_cost_usd — negative values: 0
Rows where clicks exceed impressions: 9

In [51]:
# Check whether each campaign item has multiple budget values
budget_check = (
    df_cleaned.groupby('campaign_item_id')['campaign_budget_usd']
    .nunique()
)

print(
    "Campaign items with multiple budget values:",
    (budget_check > 1).sum()
)

Campaign items with multiple budget values: 130

In [52]:
text_columns = df_cleaned.select_dtypes(
    include=['object', 'string']
).columns

for col in text_columns:
    df_cleaned[col] = df_cleaned[col].str.strip()

# Check channel names
print(df_cleaned['channel_name'].value_counts(dropna=False))

# Check platform names
print(df_cleaned['ext_service_name'].value_counts(dropna=False))

channel_name
Mobile     14625
Social     14576
Video      14525
Display    14447
Search     14439
Name: count, dtype: int64
ext_service_name
Facebook Ads    24275
DV360           24171
Google Ads      24166
Name: count, dtype: int64

In [53]:
print("Date range:")
print("Earliest:", df_cleaned['time'].min())
print("Latest:", df_cleaned['time'].max())

print("\nRecords per month:")
print(df_cleaned['time'].dt.to_period('M').value_counts().sort_index())

Date range:
Earliest: 2022-05-01 00:00:00
Latest: 2022-12-10 00:00:00

Records per month:
time
2022-05      481
2022-06     4483
2022-07     8024
2022-08     9003
2022-09     9264
2022-10    20812
2022-11    15379
2022-12     5166
Freq: M, Name: count, dtype: int64

In [54]:
# Find campaign items with multiple budget values
varying_budgets = budget_check[budget_check > 1].index

budget_examples = (
    df_cleaned[
        df_cleaned['campaign_item_id'].isin(varying_budgets)
    ]
    .sort_values('campaign_item_id')
    [['campaign_item_id', 'time', 'campaign_budget_usd',
      'media_cost_usd']]
)

print(budget_examples.head(30))

    campaign_item_id       time  campaign_budget_usd  media_cost_usd
31              2766 2022-06-26                760.0        4.166708
65              2766 2022-07-30                800.0       15.895375
66              2766 2022-07-31                800.0       34.969504
67              2766 2022-08-01                800.0       76.217342
68              2766 2022-08-02                800.0       72.066274
69              2766 2022-08-03                800.0       37.664846
70              2766 2022-08-04                800.0        5.425254
71              2766 2022-05-31                760.0       32.658344
72              2766 2022-06-01                760.0       36.156646
73              2766 2022-06-02                760.0       29.974918
19              2766 2022-06-14                760.0        9.447933
20              2766 2022-06-15                760.0       40.174019
21              2766 2022-06-16                760.0       27.732800
22              2766 2022-06-17                760.0       14.195723
23              2766 2022-06-18                760.0       18.987185
34              2766 2022-06-29                760.0        0.649222
33              2766 2022-06-28                760.0        0.815949
6               2766 2022-06-01                760.0       43.150656
7               2766 2022-06-02                760.0       31.436393
40              2766 2022-07-05                760.0        4.114127
41              2766 2022-07-06                760.0        5.853306
74              2766 2022-06-03                760.0        3.606630
75              2766 2022-06-04                760.0        5.169941
76              2766 2022-06-05                760.0       10.193957
77              2766 2022-06-06                760.0        4.913557
78              2766 2022-06-07                760.0        3.762346
79              2766 2022-06-08                760.0        7.599686
80              2766 2022-06-09                760.0        7.402583
81              2766 2022-06-10                760.0        6.238379
82              2766 2022-06-11                760.0        5.369225

In [55]:
# Compare raw and converted dates for the same rows
date_comparison = pd.DataFrame({
    'original_time': df['time'].head(30),
    'converted_time': df_cleaned['time'].head(30)
})

print(date_comparison)

   original_time converted_time
0     01-05-2022     2022-05-01
1     02-05-2022     2022-05-02
2     03-05-2022     2022-05-03
3     04-05-2022     2022-05-04
4     05-05-2022     2022-05-05
5     31-05-2022     2022-05-31
6     01-06-2022     2022-06-01
7     02-06-2022     2022-06-02
8     03-06-2022     2022-06-03
9     04-06-2022     2022-06-04
10    05-06-2022     2022-06-05
11    06-06-2022     2022-06-06
12    07-06-2022     2022-06-07
13    08-06-2022     2022-06-08
14    09-06-2022     2022-06-09
15    10-06-2022     2022-06-10
16    11-06-2022     2022-06-11
17    12-06-2022     2022-06-12
18    13-06-2022     2022-06-13
19    14-06-2022     2022-06-14
20    15-06-2022     2022-06-15
21    16-06-2022     2022-06-16
22    17-06-2022     2022-06-17
23    18-06-2022     2022-06-18
24    19-06-2022     2022-06-19
25    20-06-2022     2022-06-20
26    21-06-2022     2022-06-21
27    22-06-2022     2022-06-22
28    23-06-2022     2022-06-23
29    24-06-2022     2022-06-24

In [56]:
# Count unique campaign items per month
monthly_campaigns = (
    df_cleaned.assign(month=df_cleaned['time'].dt.to_period('M'))
    .groupby('month')['campaign_item_id']
    .nunique()
)

print(monthly_campaigns)

month
2022-05    14
2022-06    35
2022-07    65
2022-08    75
2022-09    84
2022-10    69
2022-11    35
2022-12    36
Freq: M, Name: campaign_item_id, dtype: int64

In [57]:
# Inspect budget changes for campaign item 2766
df_cleaned.loc[
    df_cleaned['campaign_item_id'] == 2766,
    ['campaign_item_id', 'time', 'campaign_budget_usd', 'media_cost_usd']
].sort_values('time')

       campaign_item_id       time  campaign_budget_usd  media_cost_usd
69200              2766 2022-05-01                760.0       43.527316
69231              2766 2022-05-01                325.0       16.368097
69201              2766 2022-05-02                760.0       33.769335
69232              2766 2022-05-02                325.0       16.669221
69233              2766 2022-05-03                325.0       21.842339
...                 ...        ...                  ...             ...
5541               2766 2022-08-04                500.0        1.458639
3123               2766 2022-08-04                800.0        0.912210
5475               2766 2022-08-04                500.0        1.924580
994                2766 2022-08-04                800.0        0.076931
730                2766 2022-08-04                800.0        0.063731

[7183 rows x 4 columns]

In [58]:
# Check exact duplicate rows
print("Exact duplicate rows:", df_cleaned.duplicated().sum())

# Check duplicate campaign-item and date combinations
print(
    "Repeated campaign-item/date combinations:",
    df_cleaned.duplicated(
        subset=['campaign_item_id', 'time']
    ).sum()
)

# Check metric validity
print("Negative clicks:", (df_cleaned['clicks'] < 0).sum())
print("Negative impressions:", (df_cleaned['impressions'] < 0).sum())
print("Negative media costs:", (df_cleaned['media_cost_usd'] < 0).sum())
print("Clicks greater than impressions:",
      (df_cleaned['clicks'] > df_cleaned['impressions']).sum())

Exact duplicate rows: 0
Repeated campaign-item/date combinations: 65534
Negative clicks: 0
Negative impressions: 0
Negative media costs: 0
Clicks greater than impressions: 9

In [59]:
# Inspect repeated campaign/date combinations
repeated = df_cleaned[
    df_cleaned.duplicated(
        subset=['campaign_item_id', 'time'],
        keep=False
    )
].sort_values(['campaign_item_id', 'time'])

print(
    repeated[
        ['campaign_item_id', 'time', 'ext_service_name',
         'creative_id', 'channel_name', 'impressions',
         'clicks', 'media_cost_usd']
    ].head(20)
)

       campaign_item_id       time ext_service_name  creative_id channel_name  \
69200              2766 2022-05-01     Facebook Ads        13715       Social
69231              2766 2022-05-01            DV360        13720       Mobile
69201              2766 2022-05-02       Google Ads        13715       Mobile
69232              2766 2022-05-02     Facebook Ads        13720       Social
69202              2766 2022-05-03     Facebook Ads        13715       Search
69233              2766 2022-05-03       Google Ads        13720       Search
69203              2766 2022-05-04       Google Ads        13715        Video
69234              2766 2022-05-04     Facebook Ads        13720       Search
69204              2766 2022-05-05     Facebook Ads        13715       Search
69235              2766 2022-05-05       Google Ads        13720       Mobile
69205              2766 2022-05-06       Google Ads        13715       Search
69236              2766 2022-05-06            DV360        13720       Mobile
69206              2766 2022-05-07            DV360        13715       Mobile
69237              2766 2022-05-07       Google Ads        13720      Display
69207              2766 2022-05-08            DV360        13715       Mobile
69238              2766 2022-05-08            DV360        13720       Search
69208              2766 2022-05-09     Facebook Ads        13715       Search
69239              2766 2022-05-09       Google Ads        13720        Video
69209              2766 2022-05-10     Facebook Ads        13715       Social
69240              2766 2022-05-10       Google Ads        13720      Display

       impressions  clicks  media_cost_usd
69200          963      14       43.527316
69231         1234      23       16.368097
69201          673       7       33.769335
69232         1079      23       16.669221
69202          752      15       40.970599
69233         1259      31       21.842339
69203          797      13       63.861270
69234         1378      63       35.844780
69204          740       6       65.153841
69235         1324      44       31.761442
69205          719      11       41.558981
69236         1372      34       31.283194
69206          696       5       38.321012
69237         1462      30        7.613418
69207          706      13       36.896404
69238         1553      26        8.756065
69208          686      10       47.889351
69239         1175      19        5.426835
69209          681      12       36.779568
69240         1500       7        4.862528

In [60]:
invalid_metrics = df_cleaned[
    df_cleaned['clicks'] > df_cleaned['impressions']
]

print(
    invalid_metrics[
        ['campaign_item_id', 'time', 'ext_service_name',
         'channel_name', 'impressions', 'clicks',
         'media_cost_usd']
    ]
)

       campaign_item_id       time ext_service_name channel_name  impressions  \
16253              2980 2022-08-31       Google Ads        Video        12174
16254              2980 2022-09-01            DV360      Display        12010
16255              2980 2022-09-02     Facebook Ads       Mobile        11975
16256              2980 2022-09-03     Facebook Ads       Mobile        11197
69556              3046 2022-08-30       Google Ads       Social         4264
70317              3054 2022-08-30            DV360      Display         8373
70319              3054 2022-09-01     Facebook Ads       Mobile         8127
70320              3054 2022-09-02            DV360       Mobile         7930
71520              3132 2022-08-30            DV360      Display         6361

       clicks  media_cost_usd
16253   13088      104.271636
16254   28401      105.155676
16255   31807       99.152455
16256   20644       84.419526
69556    4485       48.568155
70317    9650       74.622437
70319   11538       74.600952
70320   12941       74.472699
71520    7928       67.192015

In [61]:
# Inspect records where clicks exceed impressions
cols = [
    'campaign_item_id', 'time',
    'ext_service_name', 'creative_id',
    'channel_name', 'impressions', 'clicks',
    'media_cost_usd', 'campaign_budget_usd'
]

print(
    df_cleaned.loc[
        df_cleaned['clicks'] > df_cleaned['impressions'],
        cols
    ].to_string(index=False)
)

 campaign_item_id       time ext_service_name  creative_id channel_name  impressions  clicks  media_cost_usd  campaign_budget_usd
             2980 2022-08-31       Google Ads         3200        Video        12174   13088      104.271636          4322.588613
             2980 2022-09-01            DV360         3200      Display        12010   28401      105.155676          4322.588613
             2980 2022-09-02     Facebook Ads         3200       Mobile        11975   31807       99.152455          4322.588613
             2980 2022-09-03     Facebook Ads         3200       Mobile        11197   20644       84.419526          4322.588613
             3046 2022-08-30       Google Ads        13890       Social         4264    4485       48.568155          1469.123506
             3054 2022-08-30            DV360        14240      Display         8373    9650       74.622437          2241.035857
             3054 2022-09-01     Facebook Ads        14240       Mobile         8127   11538       74.600952          2241.035857
             3054 2022-09-02            DV360        14240       Mobile         7930   12941       74.472699          2241.035857
             3132 2022-08-30            DV360        14785      Display         6361    7928       67.192015          2016.932271

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72612 entries, 0 to 72611
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   campaign_item_id     72612 non-null  int64
 1   no_of_days           72612 non-null  int64
 2   time                 72612 non-null  datetime64[ns]
 3   ext_service_id       72612 non-null  int64
 4   ext_service_name     72612 non-null  object
 5   creative_id          72612 non-null  int64
 6   creative_width       69200 non-null  Int64
 7   creative_height      69200 non-null  Int64
 8   search_tags          72612 non-null  object
 9   template_id          69200 non-null  Int64
 10  landing_page         72612 non-null  object
 11  advertiser_id        72612 non-null  int64
 12  advertiser_name      72612 non-null  object
 13  network_id           72612 non-null  int64
 14  approved_budget      72206 non-null  float64
 15  advertiser_currency  72612 non-null  object
 16  channel_id           72612 non-null  int64
 17  channel_name         72612 non-null  object
 18  network_margin       72612 non-null  int64
 19  campaign_budget_usd  72612 non-null  float64
 20  impressions          72612 non-null  int64
 21  clicks               72612 non-null  int64
 22  stats_currency       72612 non-null  object
 23  currency_code        72612 non-null  object
 24  exchange_rate        72612 non-null  int64
 25  media_cost_usd       72612 non-null  float64
 26  search_tag_cat       72612 non-null  object
 27  cmi_currency_code    72612 non-null  object
 28  timezone             72612 non-null  object
 29  weekday_cat          72612 non-null  object
 30  keywords             72612 non-null  object
dtypes: Int64(3), datetime64[ns](1), float64(3), int64(11), object(13)
memory usage: 17.4+ MB

In [63]:
df_cleaned.to_csv("advertising_data_cleaned.csv", index=False)